config/routes.rb
Rorforum::Application.routes.draw do
  get "bb_code_tags/manage"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forums
  resources :topics
  resources :posts

  root to: "forums#index"
  
  match "/admin/manage_bbcode", to: "bb_code_tags#manage", via: :get
  
  match "/admin/manage_bbcode", to: "bb_code_tags#update", via: :post
  
  match "/admin/manage_forums", to: "forums#manage"

  match "/admin", to: "forums#admin"

  match "/register", to: "users#new"
  
  match "/maketopic", to: "topics#new"
  
  match "/reply", to: "posts#new"

  match "/login", to: "sessions#new"

  match '/logout', to: 'sessions#destroy', via: :delete

  match "/memberlist", to: "users#index"

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :name, :parent, :required_power_level_to_view, :required_power_level_to_post, :forum_nav_id, :description
  belongs_to :forum
  has_many :forums
  has_many :topics
  validates :forum_nav_id, uniqueness: true, presence: true
  validates :name, presence: true
  validates :parent, presence: true
  validates :required_power_level_to_view, numericality: { :only_integer => true, :greater_than_or_equal_to => -1, :less_than_or_equal_to => 3 }, presence: true 
  validates :required_power_level_to_post, numericality: { :only_integer => true, :greater_than_or_equal_to => -1, :less_than_or_equal_to => 3 }, presence: true
  
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :edit, :admin]
  before_filter :admin_user, only: [:new, :edit, :admin, :manage, :destroy]
  before_filter :check_power_level, only: [:show]

  def index
    @forum = @query = Forum.find_by_id(1)
    @topics = @forum.topics.paginate(page: params[:page])
  end

  def show
    @forum = @query = Forum.find_by_forum_nav_id(params[:id])
    @topics = @forum.topics.paginate(page: params[:page])
  end

  def new
  	@forum = @query = Forum.new
  end
  
  def create
    @forum = @query = Forum.new(params[:forum])
    if @forum.save
      flash[:success] = "Forum Created!"
      redirect_to admin_path
    else
      render 'new'
    end
  end
  
  def manage
    @forums = Forum.where("id != 1")
  end
  
  def destroy
    Forum.find(params[:id]).destroy
    flash[:success] = "Forum removed."
    redirect_to admin_manage_forums_path
  end

  def signed_in_user
  	store_location
    redirect_to login_url, notice: "Please sign in." unless signed_in?
  end

  def admin_user
    redirect_to root_path, notice: "This action is only available to administrators" unless power_level?(3)
  end
  
  def check_power_level
    redirect_to root_path, notice: "This forum doesn't exist or you do not have permission to view it" unless power_level?(Forum.find_by_forum_nav_id(params[:id]).required_power_level_to_view)
  end
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_forum.html.erb
<div class="subforums">
	<%= render :partial => "subforum", :collection => Forum.where(:parent => forum.id), :as => :forum  %>
</div>
<div class="controls-bar">
	<% if power_level?(forum.required_power_level_to_post) and signed_in? %>
		<%= link_to "Create Topic", maketopic_path(:forum => forum.forum_nav_id)%>
	<% end %>
</div>
<%= will_paginate topics%>
<div class="topics">
	<%= render @topics %>
</div>
<%= will_paginate topics%>

app/views/forums/_manageforum.html.erb
<li>
	<%= forum.name%> 
	| nav_id <%= forum.forum_nav_id%>
	| id <%= forum.id%>
	| <%= link_to "delete", forum, method: :delete,
                                  data: { confirm: "Are you sure you want to delete this forum?" } %>
	| <%= link_to "edit", edit_forum_path(forum) %>
</li>

app/views/forums/_subforum.html.erb
<% if power_level?(forum.required_power_level_to_view) %>
	<div class="subforum">
		<div class="subforum-name"><h1><%= link_to forum.name, forum_path(forum.forum_nav_id) %></h1></div>
		<div class="subforum-description"><%= forum.description %></div>
	</div>
<% end %>

app/views/forums/admin.html.erb
<%= provide(:section, "Admin panel") %>
<h1>Admin Panel</h1>
<ul>
	<li><%= link_to "Add forum", new_forum_path %></li>
	<li><%= link_to "Manage forums", admin_manage_forums_path %></li>
	<li><%= link_to "Manage BB-code", admin_manage_bbcode_path%></li>
	<li><%= link_to "Manage html filter", "#"%></li>
</ul>

app/views/forums/index.html.erb
<%= provide(:section, "Forum index") %>

<div class="forum">
	<%= render :partial => "forum", :locals => {:forum => @forum, :topics => @topics} %>
</div>

app/views/forums/manage.html.erb
<% provide(:section, 'Manage Forums') %>
<h1>Manage forums</h1>

<ul class="manage-forums">
  	<%= render :partial => "manageforum", :collection => @forums, :as => :forum  %>
</ul>

app/views/forums/new.html.erb
<%= provide(:section, "Add forum") %>
<h1>Add a forum</h1>

<div class="generic-form">
    <%= form_for(@forum) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :description %>
      <%= f.text_area :description, :size => "15x15" %>

      <%= f.label :parent %>
      <%= f.collection_select :parent, Forum.all, :id, :name%>

      <%= f.label :required_power_level_to_view %>
      <%= f.text_field :required_power_level_to_view %>

      <%= f.label :required_power_level_to_post %>
      <%= f.text_field :required_power_level_to_post %>

      <%= f.label :forum_nav_id %>
      <%= f.text_field :forum_nav_id %>      

      <%= f.submit "Make new forum", class: "btn btn-large btn-primary" %>
    <% end %>
</div>

app/views/forums/show.html.erb
<%= provide(:section, @forum.name) %>

<div class="forum">
	<div class="forum-name"><h1><%= link_to @forum.name, forum_path(@forum.forum_nav_id) %></h1></div>
	<%= render :partial => "forum", :locals => {:forum => @forum, :topics => @topics} %>
</div>