config/routes.rb
Rorforum::Application.routes.draw do
  get "bb_code_tags/manage"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forums
  resources :topics
  resources :posts

  root to: "forums#index"
  
  match "/admin/manage_bbcode", to: "bb_code_tags#manage", via: :get
  
  match "/admin/manage_bbcode", to: "bb_code_tags#update", via: :post
  
  match "/admin/manage_forums", to: "forums#manage"

  match "/admin", to: "forums#admin"

  match "/register", to: "users#new"
  
  match "/maketopic", to: "topics#new"
  
  match "/reply", to: "posts#new"

  match "/login", to: "sessions#new"

  match '/logout', to: 'sessions#destroy', via: :delete

  match "/memberlist", to: "users#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :data
  belongs_to :topic
  belongs_to :user
  default_scope order: 'posts.created_at ASC'
  validates :user_id, presence: true 
  #validates :topic_id, presence: true 
  validates :data, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :has_topic, only: [:new]
  before_filter :signed_in_user, only: [:new, :edit, :update]
  before_filter :check_forum_privileges, only: [:new, :edit, :update]
  before_filter :correct_user, only: [:edit, :update]
  
  def new
    @topic = Topic.find(params[:topic])
    @forum = @topic.forum
    @post = @query = Post.new
  end
  
  def create
    @topic = Topic.find(params[:topic])
    @post = @query = Post.new(params[:post])
    @post.topic = @topic
    @post.user = current_user
    if @post.save
      flash[:success] = "Post created!"
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  def edit
    @post = @query = Post.find(params[:id])
  end
  def update
    @post = @query = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:success] = "Post updated"
    redirect_to @post.topic
    else
      render 'edit'
    end
  end
  
  def show
    @post = Post.find(params[:id])
    redirect_to topic_path(@post.topic, :anchor => "p#{params[:id]}")
  end
  
  def has_topic
    if !params[:topic]
      redirect_to root_path
    end
  end
  
  def check_forum_privileges
    @post = Post.find(params[:id])
    @forum = @post.topic.forum
    redirect_to root_path, notice: "You do not have permission to post in this forum or it does not exist." unless @forum and power_level?(@forum.required_power_level_to_post)
  end
  
  def signed_in_user
    store_location
    redirect_to login_url, notice: "Please sign in." unless signed_in?
  end
  
  def correct_user
    @post = Post.find(params[:id])
    @user = @post.user
    redirect_to(root_path) unless current_user?(@user)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  def sanitize_and_bb postData
    data = Sanitize.clean(postData,:elements => %w[a abbr b blockquote br cite code dd dfn dl dt em i kbd li mark ol p pre
                                                   q s samp small strike strong sub sup time u ul var button])
    bbtags = BbCodeTags.where("custom = false and enabled = true").map do |tag|
      tag.enable_symbol.to_sym
    end
    
    data.bbcode_to_html({}, false, :enable, *bbtags).html_safe
  end
end

app/views/posts/_post.html.erb
<div class="post" id="p<%=post.id%>">
	<div class="top-bar">
		<div class="date">Posted on <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></div>
		<div class="controls">
			<div class="control link"><%= link_to "Link", post_path(post)%></div>
			<div class="control quote"><%= link_to "Quote", reply_path(:topic => post.topic,:quoted => post)%></div>
			<% if power_level?(1) or current_user?(post.user) %>
				<div class="control edit"><%= link_to "Edit", edit_post_path(post)%></div>
			<% end %>
		</div>
	</div>
	<div class="data">
		<div class="user-box">
			<%-# Title? -%>
			<%-# Avatar? -%>
			<div class="username"><%= link_to post.user.displayusername, user_path(post.user) %></div>
			<%-# Posts? -%>
			<%-# Since? -%>
			<%-# Location? -%>
			
		</div>
		<div class="post-box">
			<%-# Header? -%>
			<%= sanitize_and_bb post.data %> 
			<%-# Footer? -%>
		</div>
	</div>
	<div class="clear_both"></div>
</div>

app/views/posts/edit.html.erb
<%= provide(:section, "Edit post") %>
<h1>Edit post</h1>

<div class="generic-form">
	
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label "Post text" %>
      <%= f.text_area :data, :size => "15x15" %>

      <%= f.submit "Submit Post", class: "btn btn-large btn-primary" %>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= provide(:section, "New reply") %>
<h1>Create new topic</h1>

<div class="generic-form">
	
    <%= form_for(@post, :url => { :action => :create, :topic => @topic }) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label "Post text" %>
      <%= f.text_area :data, :size => "15x15" %>

      <%= f.submit "Submit Post", class: "btn btn-large btn-primary" %>
    <% end %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>