config/routes.rb
Rorforum::Application.routes.draw do
  get "bb_code_tags/manage"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forums
  resources :topics
  resources :posts

  root to: "forums#index"
  
  match "/admin/manage_bbcode", to: "bb_code_tags#manage", via: :get
  
  match "/admin/manage_bbcode", to: "bb_code_tags#update", via: :post
  
  match "/admin/manage_forums", to: "forums#manage"

  match "/admin", to: "forums#admin"

  match "/register", to: "users#new"
  
  match "/maketopic", to: "topics#new"
  
  match "/reply", to: "posts#new"

  match "/login", to: "sessions#new"

  match '/logout', to: 'sessions#destroy', via: :delete

  match "/memberlist", to: "users#index"

end

app/views/layouts/_header.html.erb
<header class="">
	<div class="logo">
	  <h1><%= link_to yield(:boardname), root_path%></h1>
	</div>
	<div class="subtitle">
		<%= yield(:boarddesc)%>
	</div>
</header>

app/views/layouts/_navigation.html.erb
<nav>
    <ul>

      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
        <li><%= link_to "Members",    memberlist_path %></li>
        <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% if power_level?(3) %>
          <li><%= link_to "Admin panel", admin_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to "Register", register_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
      
    </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= provide(:boardname, @foruminfo.name) %>
  <%= provide(:boarddesc, @foruminfo.description) %>
  <title><%= yield(:boardname) %> - <%= yield(:section) %></title>
  <%= csrf_meta_tags %>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag 'modernizr' %>

  <!-- Initializes the modernizr and actually perform the checks. Enable this
       if you need the modernizr, but remember to only do the actual checks
       that you need. -->
  <!--<#%= javascript_tag "Modernizr.load();" %>-->
  
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <!-- Add your site or application content here -->
 
	<%= render 'layouts/header' %>
	<%= render 'layouts/navigation' %>
	<div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
	<%= yield %>
    <%= debug(params) if Rails.env.development? %>
	</div>
	<div class="overflow-hidden"/>

  <!-- JavaScript at the bottom for fast page loading: http://developer.yahoo.com/performance/rules.html#js_bottom -->
  <%= javascript_include_tag 'application' %>

  <% if Rails.env.production? %>
  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
  <% end %>
</body>
</html>